"""Speech table

Revision ID: 508d6eb55b49
Revises: 01bccdcc2dd3
Create Date: 2021-04-23 17:56:59.604012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508d6eb55b49'
down_revision = '01bccdcc2dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_timestamp'), 'speech', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speech_timestamp'), table_name='speech')
    op.drop_table('speech')
    # ### end Alembic commands ###
