version: "3.7"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
        - '3306:3306'
    expose:
        - '3306'


  app:
    build: app
    restart: always
    links:
      - db
    ports: 
        - "5000:5000"
      
    

    

