version: "3.7"
services:
  app:
    build: ./microblog
    restart: always
    links:
      - db
    ports: 
        - "5000:5000"

  db:
    platform: linux/x86_64
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
          - "32000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      
    

    

