version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    networks:
        - "speech-analyzer"

  app:
    build: app
    restart: always
    ports: 
        - "5000:5000"
    networks:
        - "speech-analyzer"

networks:
    speech-analyzer:
    

