"""new fields in user, speech model

Revision ID: 8407987dd2d5
Revises: 508d6eb55b49
Create Date: 2021-04-26 12:42:13.583578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8407987dd2d5'
down_revision = '508d6eb55b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speech', sa.Column('hesitation_rate', sa.Integer(), nullable=True))
    op.add_column('speech', sa.Column('speech_length', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_column('speech', 'speech_length')
    op.drop_column('speech', 'hesitation_rate')
    # ### end Alembic commands ###
